input_boolean:
  zigbee_permit_join:
    name: 添加新设备
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: '00:03:00'

sensor:
  - platform: mqtt
    name: 网关状态
    icon: mdi:router-wireless
    state_topic: "zigbee2mqtt/bridge/state"
    value_template: >-
      {% if value | string == 'online' %}
        在线
      {% elif value | string == 'unavailable' %}
        离线
      {% endif %}