- id: '1553519761130'
  alias: 【全天】打开厨房门自动开灯
  trigger:
  - entity_id: binary_sensor.chu_fang_men_contact
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_on
  - data: {}
    entity_id: automation.chu_fang_liang_fen_zhong_wu_ren_zi_dong_guan_deng
    service: automation.turn_on
- id: '1553520045882'
  alias: 【全天】关闭厨房门自动关灯
  trigger:
  - entity_id: binary_sensor.chu_fang_men_contact
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_off
  - data: {}
    entity_id: automation.chu_fang_liang_fen_zhong_wu_ren_zi_dong_guan_deng
    service: automation.turn_off
- id: '1553520377604'
  alias: 【全天】厨房有人自动开灯
  trigger:
  - entity_id: binary_sensor.chu_fang_dong_zuo_occupancy
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_on
- id: '1553520656654'
  alias: 【全天】厨房两分钟无人自动关灯
  trigger:
  - entity_id: binary_sensor.chu_fang_dong_zuo_occupancy
    for: 00:03:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_off
- id: '1553521288162'
  alias: 【白天】打开卧室门明亮场景
  trigger:
  - entity_id: binary_sensor.wo_shi_men_contact
    platform: state
    to: 'on'
  condition:
  - after: 08:00:00
    before: 00:00:00
    condition: time
  action:
  - data:
      scene: '1'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.0x7cb03eaa0a05a30f_light
    service: light.turn_on
  - data: {}
    entity_id: automation.zou_lang_wu_ren_zi_dong_guan_deng
    service: automation.turn_on
- id: '1553521409525'
  alias: 【全天】关闭卧室门自动关灯
  trigger:
  - entity_id: binary_sensor.wo_shi_men_contact
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_off
  - data: {}
    entity_id: light.0x7cb03eaa0a05a30f_light
    service: light.turn_off
  - data: {}
    entity_id: automation.zou_lang_wu_ren_zi_dong_guan_deng
    service: automation.turn_off
- id: '1553522046658'
  alias: 【全天】走廊无人自动关闭走廊灯
  trigger:
  - entity_id: binary_sensor.zou_lang_dong_zuo_occupancy
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_off
- id: '1553522387196'
  alias: 【白天】走廊有人明亮场景
  trigger:
  - entity_id: binary_sensor.zou_lang_dong_zuo_occupancy
    platform: state
    to: 'on'
  condition:
  - after: 08:00:00
    before: 00:00:00
    condition: time
  action:
  - data:
      scene: '1'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.0x7cb03eaa0a05a30f_light
    service: light.turn_on
- id: '1553533724671'
  alias: 【夜间】打开卧室门起夜场景
  trigger:
  - entity_id: binary_sensor.wo_shi_men_contact
    platform: state
    to: 'on'
  condition:
  - after: '00:00:00:'
    before: 08:00:00
    condition: time
  action:
  - data:
      scene: '4'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.0x7cb03eaa0a05a30f_light
    service: light.turn_on
  - data: {}
    entity_id: automation.zou_lang_wu_ren_zi_dong_guan_deng
    service: automation.turn_on
- id: '1553534072049'
  alias: 【夜间】走廊有人起夜场景
  trigger:
  - entity_id: binary_sensor.zou_lang_dong_zuo_occupancy
    platform: state
    to: 'on'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data:
      scene: '4'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.0x7cb03eaa0a05a30f_light
    service: light.turn_on
- id: '1583114996904'
  alias: 【夜间】起夜自动亮灯
  description: ''
  trigger:
  - entity_id: binary_sensor.wo_shi_dong_zuo_occupancy
    platform: state
    to: 'on'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.night_light
    service: light.turn_on
- id: '1583115118210'
  alias: 【夜间】上床自动关灯
  description: ''
  trigger:
  - entity_id: binary_sensor.wo_shi_dong_zuo_occupancy
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.night_light
    service: light.turn_off
- id: '1583278034852'
  alias: 【全天】打开家门自动打开走廊灯
  description: ''
  trigger:
  - entity_id: binary_sensor.da_men_contact
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_on
- id: '1587568616889'
  alias: 【全天】魔方旋转90度开关顶灯
  description: ''
  trigger:
  - payload: flip90
    platform: mqtt
    topic: zigbee2mqtt/魔方/action
  condition: []
  action:
  - data: {}
    entity_id: light.ceiling_light
    service: light.toggle
- id: '1587641118384'
  alias: 【全天】HA启动自动重启zigbee2mqtt
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      addon: 7ad98f9c_zigbee2mqtt
    service: hassio.addon_restart
- id: '1587646123407'
  alias: 【全天】单击开关厨房插座
  description: ''
  trigger:
  - payload: single
    platform: mqtt
    topic: zigbee2mqtt/无线开关/click
  condition: []
  action:
  - data: {}
    entity_id: switch.chu_fang_cha_zuo_switch
    service: switch.toggle
