- id: '1553519761130'
  alias: 【全天】打开厨房门自动开灯
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001583bba
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_on
- id: '1553520045882'
  alias: 【全天】关闭厨房门自动关灯
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001583bba
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_off
- id: '1553520377604'
  alias: 【全天】厨房有人自动开灯
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001ad49f0
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_on
- id: '1553520656654'
  alias: 【全天】厨房两分钟无人自动关灯
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001ad49f0
    for: 00:00:30
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_light
    service: light.turn_off
- id: '1553521288162'
  alias: 【白天】打开卧室门明亮场景
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b862e7
    platform: state
    to: 'on'
  condition:
  - after: 08:00:00
    before: 00:00:00
    condition: time
  action:
  - data:
      scene: '1'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_on
- id: '1553521409525'
  alias: 【全天】关闭卧室门自动关灯
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b862e7
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_off
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_off
- id: '1553522046658'
  alias: 【全天】走廊无人自动关闭走廊灯
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000257f9fb
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_off
- id: '1553522387196'
  alias: 【白天】走廊有人明亮场景
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000257f9fb
    platform: state
    to: 'on'
  condition:
  - after: 08:00:00
    before: 00:00:00
    condition: time
  action:
  - data:
      scene: '1'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_on
- id: '1553533724671'
  alias: 【夜间】打开卧室门起夜场景
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b862e7
    platform: state
    to: 'on'
  condition:
  - after: '00:00:00:'
    before: 08:00:00
    condition: time
  action:
  - data:
      scene: '4'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_on
- id: '1553534072049'
  alias: 【夜间】走廊有人起夜场景
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000257f9fb
    platform: state
    to: 'on'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data:
      scene: '4'
    entity_id: light.doorway_light
    service: xiaomi_miio.light_set_scene
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_on
- id: '1583114996904'
  alias: 【夜间】起夜自动亮灯
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0002f98ea9
    platform: state
    to: 'on'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.night_light
    service: light.turn_on
  - data: {}
    entity_id: light.light_strip
    service: light.turn_on
- id: '1583115118210'
  alias: 【夜间】上床自动关灯
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0002f98ea9
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: 00:00:00
    before: 08:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.night_light
    service: light.turn_off
  - data: {}
    entity_id: light.light_strip
    service: light.turn_off
- id: '1583278034852'
  alias: 【全天】打开家门自动打开走廊灯
  description: ''
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001bf47c1
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.doorway_light
    service: light.turn_on
