- id: enable_zigbee_join
  alias: 【全天】开启网关添加设备
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'on'
  action:
  - data:
      payload: 'true'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.start
- id: disable_zigbee_join
  alias: 【全天】关闭网关添加设备
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: 【全天】倒计时结束关闭网关添加设备
  trigger:
  - event_data:
      entity_id: timer.zigbee_permit_join
    event_type: timer.finished
    platform: event
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: input_boolean.zigbee_permit_join
    service: input_boolean.turn_off
- id: '1588087397029'
  alias: 【全天】新设备加入网络创建通知
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/bridge/log
  condition:
  - condition: template
    value_template: '{{trigger.payload_json.type == "pairing" and trigger.payload_json.message
      == "interview_successful"}}'
  action:
  - data_template:
      title: 新设备已添加
      message: '名称: {{trigger.payload_json.meta.friendly_name}}

        型号: {{trigger.payload_json.meta.model}}

        供应商: {{trigger.payload_json.meta.vendor}}

        描述: {{trigger.payload_json.meta.description}}

        支持: {{trigger.payload_json.meta.supported}}'
    service: notify.persistent_notification
  mode: single
