homeassistant:
  name: 智能家居管理系统
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customize
  packages: !include_dir_named integrations

automation: !include automations.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace:
  # mode: yaml
  # resources:
  # - url: /local/zigbee2mqtt-networkmap.js
  #   type: module
  # - url: /local/config-template-card.js
  #   type: module
  # - url: /local/mini-media-player-bundle.js?v=1.7.0
  #   type: module

recorder:
  db_url: mysql://homeassistant:69186918@core-mariadb/homeassistant?charset=utf8

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

hassio:
config:
map:
system_health: