homeassistant:
  name: 智能家居管理系统
  latitude: 51.3
  longitude: 12.3333
  elevation: 111
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
# Show links to resources in log and frontend

# Weather
weather:
  - platform: darksky
    api_key: !secret weather_api_key

# Enables the frontend
frontend:
  themes: !include themes.yaml

# lovelace
lovelace:
  mode: yaml

# hassio
hassio:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

system_health:

zone: !include zone.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml
homekit: !include homekit.yaml
yeelight: !include yeelight.yaml
xiaomi_aqara: !include xiaomi_aqara.yaml
discovery: !include discovery.yaml
media_player: !include media_player.yaml

pi_hole:
  host: pi.hole

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload