homeassistant:
  name: 智能家居管理系统
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customize
  customize_glob: !include_dir_merge_named customize_glob
  packages: !include_dir_named integrations
  internal_url: !secret internal_url
  external_url: !secret external_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.4

automation: !include automations.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
hassio:
config:
map:
system_health:
mobile_app:
websocket_api:
my:
energy:
sun:
