homeassistant:
  name: 智能家居管理系统
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customize
  packages: !include_dir_named integrations
  internal_url: !secret internal_url
  external_url: !secret external_url

automation: !include automations.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace:
  # mode: yaml
  # resources:
  # - url: /local/zigbee2mqtt-networkmap.js
  #   type: module
  # - url: /local/config-template-card.js
  #   type: module
  # - url: /local/mini-media-player-bundle.js?v=1.7.0
  #   type: module

recorder:
hassio:
config:
map:
system_health:
mobile_app:
python_script:
websocket_api:
