- platform: xiaomi_miio
  name: Kitchen Light
  host: 192.168.1.142
  token: !secret kl_token
- platform: xiaomi_miio
  name: Doorway Light
  host: 192.168.1.14
  token: !secret dl_token
- platform: switch
  name: Ceiling Light
  entity_id: switch.shelly