custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  tab_indicator_color: var(--state-icon-active-color)
title: 智能家居管理系统
views:
  - badges: []
    cards:
      - cards:
          - entity: weather.jia
            name: 莱比锡
            type: weather-forecast
          - aspect_ratio: 75%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=51.337&lon=12.377&zoom=10&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.067&detailLon=14.383&metricWind=default&metricTemp=default&radarRange=-1
        type: vertical-stack
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.aqara_weather_temperature
            graph: line
          - type: sensor
            entity: sensor.aqara_weather_humidity
            graph: line
          - type: sensor
            entity: sensor.aqara_weather_pressure
            graph: line
      - entity: sensor.power_consumed
        type: entity
      - cards:
          - cards:
              - color_thresholds:
                  - color: "#307ffd"
                    value: 20
                  - color: "#008000"
                    value: 25
                  - color: "#e74c3c"
                    value: 30
                entities:
                  - sensor.temperature
                hours_to_show: 168
                points_per_hour: 0.25
                type: custom:mini-graph-card
              - color_thresholds:
                  - color: "#008000"
                    value: 30
                  - color: "#ff9900"
                    value: 50
                  - color: "#e74c3c"
                    value: 70
                entities:
                  - sensor.humidity
                hours_to_show: 168
                points_per_hour: 0.25
                type: custom:mini-graph-card
            type: horizontal-stack
          - cards:
              - entities:
                  - aggregate_func: max
                    color: null
                    entity: sensor.power_loaded
                    name: 最高
                  - aggregate_func: min
                    entity: sensor.power_loaded
                    name: 最低
                  - aggregate_func: avg
                    color: green
                    entity: sensor.power_loaded
                    name: 平均
                hours_to_show: 24
                name: 功率
                type: custom:mini-graph-card
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: sensor.germany_coronavirus_current
            name: 现存
        hours_to_show: 168
        name: 德国疫情
        type: custom:mini-graph-card
      - entities:
          - entity: light.ceiling_light
            tap_action:
              action: toggle
          - entity: light.doorway_light
            tap_action:
              action: toggle
          - entity: light.toilet_light
            tap_action:
              action: toggle
          - entity: light.kitchen_light
            tap_action:
              action: toggle
          - entity: light.night_light
            tap_action:
              action: toggle
        type: glance
      - card:
          title: 激活的传感器
          type: glance
        entities:
          - entity: binary_sensor.home_door
          - entity: binary_sensor.bedroom_door
          - entity: binary_sensor.kitchen_door
          - entity: binary_sensor.doorway_motion
          - entity: binary_sensor.toilet_motion
          - entity: binary_sensor.kitchen_motion
        show_empty: false
        state_filter:
          - "on"
        type: entity-filter
      - entities:
          - entity: switch.adguard_protection
          - entity: sensor.adguard_average_processing_speed
        show_header_toggle: false
        type: entities
      - entities:
          - entity: switch.kitchen_socket
          - entity: switch.induktion_socket
          - entity: switch.bedside_socket
          - entity: switch.desk_socket
          - entity: switch.floor_socket
        show_header_toggle: false
        type: entities
    icon: mdi:home
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 3000
        height: 700
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        type: custom:zigbee2mqtt-networkmap
    icon: mdi:chart-bubble
    panel: true
    path: networkmap
    title: Networkmap
  - badges: []
    cards:
      - entity: sensor.uptime
        type: entity
      - entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.wang_guan_zhuang_tai
          - entity: script.homeassistant_restart
          - entity: binary_sensor.ping_192_168_1_23
          - entity: switch.pc_switch
        show_header_toggle: false
        title: 系统
        type: entities
      - entities:
          - aggregate_func: max
            color: null
            entity: sensor.cpu_temperature
            name: 最高
          - aggregate_func: min
            entity: sensor.cpu_temperature
            name: 最低
          - aggregate_func: avg
            color: green
            entity: sensor.cpu_temperature
            name: 平均
        hours_to_show: 24
        name: CPU温度
        type: custom:mini-graph-card
      - type: entities
        entities:
          - entity: sensor.transmission_active_torrents
          - entity: sensor.transmission_completed_torrents
          - entity: sensor.transmission_down_speed
          - entity: sensor.transmission_status
          - entity: sensor.transmission_up_speed
        title: Transmission
      - type: entities
        entities:
          - entity: binary_sensor.minecraft_server_status
          - entity: sensor.minecraft_server_latency_time
          - entity: sensor.minecraft_server_players_max
          - entity: sensor.minecraft_server_players_online
          - entity: sensor.minecraft_server_protocol_version
          - entity: sensor.minecraft_server_version
        title: Minecraft 服务器
    icon: mdi:server-network
    path: panel
    title: PANEL
