title: 智能家居管理系统
views:
  - badges:
      - entity: person.zhang_yao_wei
    cards:
      - cards:
          - entity: weather.jia
            name: 莱比锡
            type: weather-forecast
          - aspect_ratio: 75%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=51.337&lon=12.377&zoom=10&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.067&detailLon=14.383&metricWind=default&metricTemp=default&radarRange=-1
        type: vertical-stack
      - entity: sensor.power_consumed
        type: entity
      - cards:
          - cards:
              - entity: sensor.0x00158d000149c947_temperature
                graph: line
                type: sensor
              - entity: sensor.0x00158d000149c947_humidity
                graph: line
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.power_loaded
                graph: line
                type: sensor
              - entity: sensor.cpu_temperature
                graph: line
                type: sensor
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: sensor.germany_coronavirus_confirmed
          - entity: sensor.germany_coronavirus_current
          - entity: sensor.germany_coronavirus_recovered
          - entity: sensor.germany_coronavirus_deaths
        type: glance
      - entities:
          - entity: light.ceiling_light
            tap_action:
              action: toggle
          - entity: light.doorway_light
            tap_action:
              action: toggle
          - entity: light.toilet_light
            tap_action:
              action: toggle
          - entity: light.night_light
            tap_action:
              action: toggle
          - entity: light.kitchen_light
            tap_action:
              action: toggle
        type: glance
      - entities:
          - entity: sensor.adguard_average_processing_speed
          - entity: switch.adguard_protection
        show_header_toggle: false
        type: entities
      - entities:
          - entity: binary_sensor.0x00158d0001bf47c1_contact
          - entity: binary_sensor.0x00158d0001b862e7_contact
          - entity: binary_sensor.0x00158d0001583bba_contact
          - entity: binary_sensor.0x00158d00010f84dd_occupancy
          - entity: binary_sensor.0x00158d000257f9fb_occupancy
          - entity: binary_sensor.0x00158d0002f98ea9_occupancy
          - entity: binary_sensor.0x00158d0001ad49f0_occupancy
        show_icon: true
        show_name: true
        show_state: true
        title: 传感器
        type: glance
      - entities:
          - entity: switch.0x00158d000154b2cb_switch
          - entity: switch.0x00158d0001e89755_switch
          - entity: switch.0x00158d0001e8975b_switch
          - entity: switch.0x00158d000236c60a_switch
          - entity: switch.0x00158d00012db5eb_switch
          - entity: switch.wake_on_lan
        show_header_toggle: false
        type: entities
    panel: false
    path: default_view
    title: Home
  - title: Networkmap
    path: networkmap
    panel: true
    cards: 
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        # the following are optional:
        mqtt_base_topic: zigbee2mqtt # if you change base_topic of Zigbee2mqtt, change it accordingly
        force: 3000 # decrease it to get smaller map if you have many devices
        node_size: 16
        font_size: 12
        link_width: 2
        height: 600 # height of the card
        # use this css config or use whatever css tech to change look and feel,
        # the same variable can also be used in Home Assistant themes, see https://www.home-assistant.io/components/frontend/#defining-themes
        css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
