custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  tab_indicator_color: var(--state-icon-active-color)
title: 智能家居管理系统
views:
  - badges: []
    cards:
      - cards:
          - entity: weather.jia
            name: 莱比锡
            type: weather-forecast
          - aspect_ratio: 75%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=51.337&lon=12.377&zoom=10&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.067&detailLon=14.383&metricWind=default&metricTemp=default&radarRange=-1
        type: vertical-stack
      - entity: sensor.power_consumed
        type: entity
      - cards:
          - cards:
              - color_thresholds:
                  - color: '#307ffd'
                    value: 20
                  - color: '#008000'
                    value: 25
                  - color: '#e74c3c'
                    value: 30
                entities:
                  - sensor.temp_humidity_sensor_temperature
                hours_to_show: 168
                points_per_hour: 0.25
                type: 'custom:mini-graph-card'
              - color_thresholds:
                  - color: '#008000'
                    value: 30
                  - color: '#ff9900'
                    value: 50
                  - color: '#e74c3c'
                    value: 70
                entities:
                  - sensor.temp_humidity_sensor_humidity
                hours_to_show: 168
                points_per_hour: 0.25
                type: 'custom:mini-graph-card'
            type: horizontal-stack
          - cards:
              - entities:
                  - aggregate_func: max
                    color: null
                    entity: sensor.power_loaded
                    name: 最高
                  - aggregate_func: min
                    entity: sensor.power_loaded
                    name: 最低
                  - aggregate_func: avg
                    color: green
                    entity: sensor.power_loaded
                    name: 平均
                hours_to_show: 24
                name: 功率
                type: 'custom:mini-graph-card'
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: fan.my_fan
            tap_action:
              action: call-service
              service: fan.toggle
              service_data:
                entity_id: fan.my_fan
          - entity: switch.oscillate
            icon: 'mdi:rotate-3d-variant'
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.oscillate
          - entity: zone.home
            icon: 'mdi:numeric-1'
            name: null
            tap_action:
              action: call-service
              service: fan.set_speed
              service_data:
                entity_id: fan.my_fan
                speed: 1
          - entity: zone.home
            icon: 'mdi:numeric-2'
            name: 档位
            tap_action:
              action: call-service
              service: fan.set_speed
              service_data:
                entity_id: fan.my_fan
                speed: 2
          - entity: zone.home
            icon: 'mdi:numeric-3'
            name: null
            tap_action:
              action: call-service
              service: fan.set_speed
              service_data:
                entity_id: fan.my_fan
                speed: 3
        show_icon: true
        show_name: true
        show_state: false
        type: glance
      - artwork: cover
        entity: media_player.srs_x99
        hide:
          controls: true
          icon_state: false
          power_state: false
        type: 'custom:mini-media-player'
      - entities:
          - entity: sensor.germany_coronavirus_current
            name: 现存
          - sensor.germany_coronavirus_confirmed
          - sensor.germany_coronavirus_deaths
          - sensor.germany_coronavirus_recovered
        hours_to_show: 168
        name: 德国疫情
        type: 'custom:mini-graph-card'
      - entities:
          - entity: light.ceiling_light
            tap_action:
              action: toggle
          - entity: light.doorway_light
            tap_action:
              action: toggle
          - entity: light.0x7cb03eaa0a00c711_light
            tap_action:
              action: toggle
          - entity: light.kitchen_light
            tap_action:
              action: toggle
          - entity: light.night_light
            tap_action:
              action: toggle
        type: glance
      - entities:
          - entity: switch.adguard_protection
          - entity: sensor.adguard_average_processing_speed
        show_header_toggle: false
        type: entities
      - card:
          title: 激活的传感器
          type: glance
        entities:
          - entity: binary_sensor.da_men_contact
          - entity: binary_sensor.wo_shi_men_contact
          - entity: binary_sensor.chu_fang_men_contact
          - entity: binary_sensor.wei_sheng_jian_dong_zuo_occupancy
          - entity: binary_sensor.zou_lang_dong_zuo_occupancy
          - entity: binary_sensor.wo_shi_dong_zuo_occupancy
          - entity: binary_sensor.chu_fang_dong_zuo_occupancy
        state_filter:
          - 'on'
        type: entity-filter
        show_empty: false
      - entities:
          - entity: switch.chu_fang_cha_zuo_switch
          - entity: switch.chuang_tou_cha_zuo_switch
          - entity: switch.zhuo_xia_cha_zuo_switch
          - entity: switch.di_xia_cha_zuo_switch
        show_header_toggle: false
        type: entities
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: Home
  - badges: []
    cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 3000
        height: 700
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        type: 'custom:zigbee2mqtt-networkmap'
    icon: 'mdi:chart-bubble'
    panel: true
    path: networkmap
    title: Networkmap
  - badges: []
    cards:
      - aspect_ratio: 100%
        type: iframe
        url: 'https://nr.awyun.top'
    icon: 'mdi:sitemap'
    panel: true
    title: Node-RED
  - badges: []
    cards:
      - entity: sensor.uptime
        type: entity
      - entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.wang_guan_zhuang_tai
          - entity: script.homeassistant_restart
          - entity: binary_sensor.ping_binary_sensor
          - entity: switch.pc_switch
        show_header_toggle: false
        title: 系统
        type: entities
      - entities:
          - aggregate_func: max
            color: null
            entity: sensor.cpu_temperature
            name: 最高
          - aggregate_func: min
            entity: sensor.cpu_temperature
            name: 最低
          - aggregate_func: avg
            color: green
            entity: sensor.cpu_temperature
            name: 平均
        hours_to_show: 24
        name: CPU温度
        type: 'custom:mini-graph-card'
      - entities:
          - entity: sensor.weekly_energy
        name: ENERGY CONSUMPTION
        show:
          graph: bar
        type: 'custom:mini-graph-card'
    icon: 'mdi:server-network'
    path: panel
    title: PANEL
