title: 智能家居管理系统
views:
  - icon: mdi:home
    panel: false
    path: default_view
    title: Home
    badges: []
    cards:
      - cards:
          - entity: weather.jia
            name: 莱比锡
            type: weather-forecast
          - aspect_ratio: 50%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=51.337&lon=12.377&zoom=10&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.067&detailLon=14.383&metricWind=default&metricTemp=default&radarRange=-1
        type: vertical-stack
      - type: custom:sun-card
      - entity: sensor.power_consumed
        type: entity
      - type: horizontal-stack
        cards:
          - hours_to_show: 24
            graph: line
            type: sensor
            entity: sensor.0x00158d00068b7b55_temperature
            detail: 1
          - hours_to_show: 24
            graph: line
            type: sensor
            entity: sensor.0x00158d00068b7b55_humidity
            detail: 1
          - hours_to_show: 24
            graph: line
            type: sensor
            entity: sensor.0x00158d00068b7b55_pressure
            detail: 1
      - cards:
          - cards:
              - color_thresholds:
                  - color: "#307ffd"
                    value: 20
                  - color: "#008000"
                    value: 25
                  - color: "#e74c3c"
                    value: 30
                entities:
                  - sensor.temperature
                hours_to_show: 168
                points_per_hour: 0.25
                type: custom:mini-graph-card
              - color_thresholds:
                  - color: "#008000"
                    value: 30
                  - color: "#ff9900"
                    value: 50
                  - color: "#e74c3c"
                    value: 70
                entities:
                  - sensor.humidity
                hours_to_show: 168
                points_per_hour: 0.25
                type: custom:mini-graph-card
            type: horizontal-stack
          - cards:
              - entities:
                  - aggregate_func: max
                    color: null
                    entity: sensor.power_loaded
                    name: 最高
                  - aggregate_func: min
                    entity: sensor.power_loaded
                    name: 最低
                  - aggregate_func: avg
                    color: green
                    entity: sensor.power_loaded
                    name: 平均
                hours_to_show: 24
                name: 功率
                type: custom:mini-graph-card
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: light.ceiling_light
            tap_action:
              action: toggle
          - entity: light.doorway_light
            tap_action:
              action: toggle
          - entity: light.0x7cb03eaa0a00c711
            tap_action:
              action: toggle
          - entity: light.kitchen_light
            tap_action:
              action: toggle
          - entity: light.night_light
            tap_action:
              action: toggle
        type: glance
      - card:
          title: 激活的传感器
          type: glance
        entities:
          - entity: binary_sensor.0x00158d0001bf47c1_contact
          - entity: binary_sensor.0x00158d0001b862e7_contact
          - entity: binary_sensor.0x00158d0001583bba_contact
          - entity: binary_sensor.0x00158d000257f9fb_occupancy
          - entity: binary_sensor.0x00158d0002f98ea9_occupancy
          - entity: binary_sensor.0x00158d00010f84dd_occupancy
        show_empty: false
        state_filter:
          - "on"
        type: entity-filter
      - entities:
          - entity: switch.adguard_protection
          - entity: sensor.adguard_average_processing_speed
        show_header_toggle: false
        type: entities
      - entities:
          - entity: switch.0x00158d000154b2cb
          - entity: switch.0x00158d00012db5eb
          - entity: switch.0x00158d0001e8975b
          - entity: switch.0x00158d0001e89755
          - entity: switch.0x00158d000236c60a
        show_header_toggle: false
        type: entities
  - badges: []
    cards:
      - entity: sensor.uptime
        type: entity
      - entities:
          - entity: sensor.wang_guan_zhuang_tai
          - entity: binary_sensor.ping_192_168_1_23
          - entity: switch.pc_switch
        show_header_toggle: false
        title: 系统
        type: entities
      - type: entities
        entities:
          - entity: sensor.qbittorrent_status
          - entity: sensor.qbittorrent_down_speed
          - entity: sensor.qbittorrent_up_speed
        title: qBittorrent
    icon: mdi:server-network
    path: panel
    title: PANEL
