title: 智能家居管理系统
views:
  - badges: null
    cards:
      - cards:
          - entity: weather.jia
            name: 莱比锡
            type: weather-forecast
          - aspect_ratio: 75%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=51.337&lon=12.377&zoom=10&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.067&detailLon=14.383&metricWind=default&metricTemp=default&radarRange=-1
        type: vertical-stack
      - entity: sensor.power_consumed
        type: entity
      - cards:
          - cards:
              - entity: sensor.wen_shi_du_chuan_gan_qi_temperature
                graph: line
                type: sensor
              - entity: sensor.wen_shi_du_chuan_gan_qi_humidity
                graph: line
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.power_loaded
                graph: line
                type: sensor
              - entity: sensor.cpu_temperature
                graph: line
                type: sensor
            type: horizontal-stack
        type: vertical-stack
      - entity: media_player.srs_x99
        hide:
          controls: true
          icon_state: false
          power_state: false
        type: 'custom:mini-media-player'
      - entities:
          - entity: sensor.germany_coronavirus_confirmed
          - entity: sensor.germany_coronavirus_current
          - entity: sensor.germany_coronavirus_recovered
          - entity: sensor.germany_coronavirus_deaths
        type: glance
      - entities:
          - entity: light.ceiling_light
            tap_action:
              action: toggle
          - entity: light.doorway_light
            tap_action:
              action: toggle
          - entity: light.0x7cb03eaa0a05a30f_light
            tap_action:
              action: toggle
          - entity: light.night_light
            tap_action:
              action: toggle
          - entity: light.kitchen_light
            tap_action:
              action: toggle
        type: glance
      - entities:
          - entity: switch.adguard_protection
          - entity: sensor.adguard_average_processing_speed
        show_header_toggle: false
        type: entities
      - entities:
          - entity: binary_sensor.da_men_contact
          - entity: binary_sensor.wo_shi_men_contact
          - entity: binary_sensor.chu_fang_men_contact
          - entity: binary_sensor.wei_sheng_jian_dong_zuo_occupancy
          - entity: binary_sensor.zou_lang_dong_zuo_occupancy
          - entity: binary_sensor.wo_shi_dong_zuo_occupancy
          - entity: binary_sensor.chu_fang_dong_zuo_occupancy
        show_icon: true
        show_name: true
        show_state: true
        title: 传感器
        type: glance
      - entities:
          - entity: switch.chu_fang_cha_zuo_switch
          - entity: switch.chuang_tou_cha_zuo_switch
          - entity: switch.zhuo_xia_cha_zuo_switch
          - entity: switch.di_xia_cha_zuo_switch
          - entity: switch.xi_yi_ji_cha_zuo_switch
          - entity: switch.wake_on_lan
        show_header_toggle: false
        type: entities
    panel: false
    path: default_view
    title: Home
  - cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 3000
        height: 700
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        type: 'custom:zigbee2mqtt-networkmap'
    panel: true
    path: networkmap
    title: Networkmap
  - badges: []
    cards:
      - entities:
          - entity: automation.quan_tian_da_kai_jia_men_zi_dong_da_kai_zou_lang_deng
          - entity: automation.guan_bi_wo_shi_men_zi_dong_guan_deng
          - entity: automation.zou_lang_wu_ren_zi_dong_guan_deng
          - entity: automation.bai_tian_da_kai_wo_shi_men_ming_liang_chang_jing
          - entity: automation.bai_tian_zou_lang_you_ren_ming_liang_chang_jing
          - entity: automation.ye_jian_da_kai_wo_shi_men_qi_ye_chang_jing
          - entity: automation.ye_jian_zou_lang_you_ren_qi_ye_chang_jing
        title: 走廊
        type: entities
      - entities:
          - entity: automation.haqi_dong_zhong_qi_zigbee2mqtt
          - entity: automation.quan_tian_mo_fang_xuan_zhuan_90du_kai_guan_ding_deng
          - entity: automation.enable_zigbee_joining
          - entity: automation.disable_zigbee_joining
          - entity: automation.disable_zigbee_joining_by_timer
          - entity: automation.ye_jian_qi_ye_zi_dong_liang_deng
          - entity: automation.ye_jian_shang_chuang_zi_dong_guan_deng
        title: 卧室
        type: entities
      - entities:
          - entity: automation.da_kai_chu_fang_men_zi_dong_kai_deng
          - entity: automation.guan_bi_chu_fang_men_zi_dong_guan_deng
          - entity: automation.chu_fang_you_ren_zi_dong_kai_deng
          - entity: automation.chu_fang_liang_fen_zhong_wu_ren_zi_dong_guan_deng
          - entity: automation.quan_tian_dan_ji_kai_guan_chu_fang_cha_zuo
        title: 厨房
        type: entities
    path: automation
    title: AUTOMATION
  - badges: []
    cards:
      - entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.wang_guan_zhuang_tai
          - entity: script.homeassistant_restart
        show_header_toggle: false
        title: 系统
        type: entities
      - entities:
          - entity: sensor.chu_fang_cha_zuo_linkquality
          - entity: sensor.chu_fang_dong_zuo_linkquality
          - entity: sensor.chu_fang_men_linkquality
          - entity: sensor.chuang_tou_cha_zuo_linkquality
          - entity: sensor.da_men_linkquality
          - entity: sensor.di_xia_cha_zuo_linkquality
          - entity: sensor.mo_fang_linkquality
          - entity: sensor.wei_sheng_jian_dong_zuo_linkquality
          - entity: sensor.wen_shi_du_chuan_gan_qi_linkquality
          - entity: sensor.wo_shi_dong_zuo_linkquality
          - entity: sensor.wo_shi_men_linkquality
          - entity: sensor.wu_xian_kai_guan_linkquality
          - entity: sensor.xi_yi_ji_cha_zuo_linkquality
          - entity: sensor.zhuo_xia_cha_zuo_linkquality
          - entity: sensor.zou_lang_dong_zuo_linkquality
        type: glance
    path: panel
    title: PANEL
