# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      power_loaded:
        friendly_name: "总功率"
        unit_of_measurement: 'W'
        value_template: "{{ (state_attr('sensor.chu_fang_cha_zuo_power', 'power') + state_attr('sensor.chuang_tou_cha_zuo_power', 'power') + state_attr('sensor.di_xia_cha_zuo_power', 'power') + state_attr('sensor.xi_yi_ji_cha_zuo_power', 'power') + state_attr('sensor.zhuo_xia_cha_zuo_power', 'power')) | int }}"