# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      power_consumed:
        friendly_name: "总耗电量"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.chu_fang_cha_zuo_power', 'consumption') + state_attr('sensor.chuang_tou_cha_zuo_power', 'consumption') + state_attr('sensor.di_xia_cha_zuo_power', 'consumption') + state_attr('sensor.xi_yi_ji_cha_zuo_power', 'consumption') + state_attr('sensor.zhuo_xia_cha_zuo_power', 'consumption')) | int }}"