# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      power_loaded:
        friendly_name: "总功率"
        unit_of_measurement: "W"
        value_template: "{{ (state_attr('sensor.kitchen_socket_power', 'power') + state_attr('sensor.bedside_socket_power', 'power') + state_attr('sensor.floor_socket_power', 'power') + state_attr('sensor.desk_socket_power', 'power')) | int }}"
      power_consumed:
        friendly_name: "总耗电量"
        unit_of_measurement: "kWh"
        value_template: "{{ (state_attr('sensor.kitchen_socket_consumption', 'consumption') + state_attr('sensor.bedside_socket_consumption', 'consumption') + state_attr('sensor.floor_socket_consumption', 'consumption') + state_attr('sensor.desk_socket_consumption', 'consumption')) | int }}"
      power_consumed_daily:
        friendly_name: "日耗电量"
        unit_of_measurement: "kWh"
        value_template: "{{ states('sensor.daily_energy')|float }}"
      power_consumed_monthly:
        friendly_name: "月耗电量"
        unit_of_measurement: "kWh"
        value_template: "{{ states('sensor.monthly_energy')|float }}"
